# Constants for the application
INTERVALS = ["5m", "15m", "30m", "60m", "1h", "1d"]
SCORE_KEY = "score"
HISTORY_KEY = "history"

# --- Defaults ---
DEFAULT_SYMBOL = "AAPL"
DEFAULT_INTERVAL = "1d"
DEFAULT_PREDICTION_CANDLES = 25
MIN_PREDICTION_CANDLES = 10
MAX_PREDICTION_CANDLES = 50
PREDICTION_CANDLES_STEP = 5
MIN_REQUIRED_DATA_POINTS = 45  # Base requirement before adding prediction candles


# -- Stock Universes --
STOCK_UNIVERSES = {
    "Nifty 50": [
        "RELIANCE.NS", "TCS.NS", "HDFCBANK.NS", "INFY.NS", "ICICIBANK.NS",
        "HINDUNILVR.NS", "ITC.NS", "LT.NS", "KOTAKBANK.NS", "HDFC.NS",
        "BAJFINANCE.NS", "BHARTIARTL.NS", "AXISBANK.NS", "SBIN.NS", "ASIANPAINT.NS",
        "MARUTI.NS", "NESTLEIND.NS", "TITAN.NS", "WIPRO.NS", "ULTRACEMCO.NS",
        "POWERGRID.NS", "NTPC.NS", "M&M.NS", "SUNPHARMA.NS", "HCLTECH.NS",
        "GRASIM.NS", "BAJAJFINSV.NS", "ADANIPORTS.NS", "JSWSTEEL.NS", "TATACONSUM.NS",
        "ONGC.NS", "TECHM.NS", "DIVISLAB.NS", "LTIM.NS", "APOLLOHOSP.NS",
        "CIPLA.NS", "HINDALCO.NS", "DMART.NS", "SRF.NS", "COALINDIA.NS",
        "BPCL.NS", "HEROMOTOCO.NS", "EICHERMOT.NS", "ADANIENT.NS", "UPL.NS",
        "INDUSINDBK.NS", "TATAMOTORS.NS", "SBILIFE.NS", "SHREECEM.NS", "DRREDDY.NS"
    ],
    "Popular US Stocks": [
        "AAPL", "MSFT", "GOOG", "AMZN", "TSLA", "META", "NVDA", "JPM", "V",
        "UNH", "JNJ", "XOM", "WMT", "PG", "HD", "DIS", "PYPL", "NFLX"
    ],
    "Cryptocurrencies": [
        "BTC-USD", "ETH-USD", "USDT-USD", "BNB-USD", "XRP-USD", "USDC-USD", "ADA-USD",
        "DOGE-USD", "SOL-USD", "TRX-USD"
    ],
    "Nifty 500": [
        "RELIANCE.NS", "TCS.NS", "HDFCBANK.NS", "INFY.NS", "ICICIBANK.NS", "HINDUNILVR.NS", "ITC.NS", "LT.NS", "KOTAKBANK.NS", "HDFC.NS", "BAJFINANCE.NS", "BHARTIARTL.NS", "AXISBANK.NS", "SBIN.NS", "ASIANPAINT.NS", "MARUTI.NS", "NESTLEIND.NS", "TITAN.NS", "WIPRO.NS", "ULTRACEMCO.NS", "POWERGRID.NS", "NTPC.NS", "M&M.NS", "SUNPHARMA.NS", "HCLTECH.NS", "GRASIM.NS", "BAJAJFINSV.NS", "ADANIPORTS.NS", "JSWSTEEL.NS", "TATACONSUM.NS", "ONGC.NS", "TECHM.NS", "DIVISLAB.NS", "LTIM.NS", "APOLLOHOSP.NS", "CIPLA.NS", "HINDALCO.NS", "DMART.NS", "SRF.NS", "COALINDIA.NS", "BPCL.NS", "HEROMOTOCO.NS", "EICHERMOT.NS", "ADANIENT.NS", "UPL.NS", "INDUSINDBK.NS", "TATAMOTORS.NS", "SBILIFE.NS", "SHREECEM.NS", "DRREDDY.NS", "ADANIENSOL.NS", "PIDILITIND.NS", "BRITANNIA.NS", "LICI.NS", "VEDL.NS", "SIEMENS.NS", "DLF.NS", "JSWENERGY.NS", "HDFCLIFE.NS", "SAMVRDNA.NS", "PAGEIND.NS", "CONCOR.NS", "GAIL.NS", "ABB.NS", "MUTHOOTFIN.NS", "PAYTM.NS", "GODREJCP.NS", "NMDC.NS", "PETRONET.NS", "IDFCFIRSTB.NS", "HAL.NS", "PIIND.NS", "COLPAL.NS", "MCDOWELL-N.NS", "BANKBARODA.NS", "BEL.NS", "CANBK.NS", "IRCTC.NS", "POLYCAB.NS", "BANDHANBNK.NS", "ALKEM.NS", "CHOLAFIN.NS", "GLENMARK.NS", "FEDERALBNK.NS", "ZOMATO.NS", "TVSMOTOR.NS", "SAIL.NS", "JUBLFOOD.NS", "ACC.NS", "AUBANK.NS", "BOSCHLTD.NS", "SRTRANSFIN.NS", "GLAND.NS", "ICICIGI.NS", "LUPIN.NS", "PERSISTENT.NS", "CUMMINSIND.NS", "RECLTD.NS", "M&MFIN.NS", "MOTILALFSL.NS", "ASTRAL.NS", "CROMPTON.NS", "INDIAMART.NS", "PVRINOX.NS", "RAIN.NS", "MPHASIS.NS", "ICICIPRULI.NS", "IDEA.NS", "TATACHEM.NS", "DEEPAKNTR.NS", "ABFRL.NS", "SYNGENE.NS", "PNB.NS", "RAMCOCEM.NS", "TATAELXSI.NS", "VEDANTA.NS", "DIXON.NS", "LICHSGFIN.NS", "NAVINFLUOR.NS", "AARTIIND.NS", "BALKRISIND.NS", "JKCEMENT.NS", "RVNL.NS", "CGPOWER.NS", "TATASTEEL.NS", "IRFC.NS", "JKTYRE.NS", "CANFINHOME.NS", "MAHLOG.NS", "TIMKEN.NS", "DELTACORP.NS", "LAURUSLABS.NS", "LTTS.NS", "TRIDENT.NS", "IIFLFIN.NS", "SUZLON.NS", "ZENSARTECH.NS", "TRATON.NS", "NETWORK18.NS", "MAHINDCIE.NS", "ORIENTCEM.NS", "HFCL.NS", "WELCORP.NS", "KPRMILL.NS", "GMRINFRA.NS", "VAIBHAVGBL.NS", "ADANIGREEN.NS", "FACT.NS", "GRINDWELL.NS", "JBCHEPHARM.NS", "KARURVYSYA.NS", "KALYANKJIL.NS", "KPITTECH.NS", "MASTEK.NS", "NCC.NS", "PGHL.NS", "PRESTIGE.NS", "RBA.NS", "SHILPAMED.NS", "SOLARINDS.NS", "STARHEALTH.NS", "TATAPOWER.NS", "TECHNOE.NS", "THERMAX.NS", "TITANIC.NS", "TRIVENI.NS", "UJJIVANSFB.NS", "VRLLOG.NS", "YESBANK.NS", "ZEEL.NS", "ADANITRANS.NS", "APARINDS.NS", "ASAHIINDIA.NS", "ASHOKLEY.NS", "BAJAJELEC.NS", "BALRAMCHIN.NS", "BASF.NS", "BATAINDIA.NS", "BLUEDART.NS", "BORORENEW.NS", "CENTRALBK.NS", "CHAMBLFERT.NS", "COCHINSHIP.NS", "CONTPET.NS", "CROMPTON.NS", "CYIENT.NS", "DATAPATTNS.NS", "DCMSHRIRAM.NS", "DHARMSHREE.NS", "EIHOTEL.NS", "ELGIEQUIP.NS", "EMAMILTD.NS", "ESCORTS.NS", "EQUITASBNK.NS", "ESABINDIA.NS", "FINCABLES.NS", "FORTIS.NS", "FSL.NS", "GABRIEL.NS", "GARFIBRES.NS", "GENUSPOWER.NS", "GESHIP.NS", "GICRE.NS", "GODFRYPHLP.NS", "GODREJAGRO.NS", "GRANULES.NS", "GREENLAM.NS", "GSPL.NS", "GTPL.NS"
    ]
}